In [14]:
#UNION
A = dict()
B = dict()
Y = dict()

A = {"a": 0.2, "b": 0.3, "c": 0.6, "d": 0.6}
B = {"a": 0.9, "b": 0.9, "c": 0.4, "d": 0.5}

for A_key, B_key in zip(A, B):
    A_value = A[A_key]
    B_value = B[B_key]

    if A_value > B_value:
        Y[A_key] = A_value
    else:
        Y[B_key] = B_value
print('Fuzzy Set Union is :', Y)


Fuzzy Set Union is : {'a': 0.9, 'b': 0.9, 'c': 0.6, 'd': 0.6}


In [15]:
#INTERSECTION
for A_key, B_key in zip(A, B):
    A_value = A[A_key]
    B_value = B[B_key]
 
    if A_value < B_value:
        Y[A_key] = A_value
    else:
        Y[B_key] = B_value
print('Fuzzy Set Intersection is :', Y)

Fuzzy Set Intersection is : {'a': 0.2, 'b': 0.3, 'c': 0.4, 'd': 0.5}


In [16]:
#COMPLEMENT
for A_key in A:
    Y[A_key]= 1-A[A_key]
         
print('Fuzzy Set Complement is :', Y)

Fuzzy Set Complement is : {'a': 0.8, 'b': 0.7, 'c': 0.4, 'd': 0.4}


In [7]:
#DIFFERENCE
for A_key, B_key in zip(A, B):
    A_value = A[A_key]
    B_value = B[B_key]
    B_value = 1 - B_value
 
    if A_value < B_value:
        Y[A_key] = A_value
    else:
        Y[B_key] = B_value
         
print('Fuzzy Set Difference is :', Y)

Fuzzy Set Difference is : {'a': 0.09999999999999998, 'b': 0.09999999999999998, 'c': 0.6, 'd': 0.5}


In [11]:
#CARTESIAN PRODUCT
import numpy as np
import skfuzzy as fuzz

cartesian_product = fuzz.cartprod(np.array(list(A.values())), np.array(list(B.values())))
print("Cartesian product:", cartesian_product)

Cartesian product: [[0.2 0.2 0.2 0.2]
 [0.3 0.3 0.3 0.3]
 [0.6 0.6 0.4 0.5]
 [0.6 0.6 0.4 0.5]]


In [1]:
!pip install scikit-fuzzy

     ---------------------------------------- 0.0/994.0 kB ? eta -:--:--
     --- ----------------------------------- 92.2/994.0 kB 5.1 MB/s eta 0:00:01
     ----- -------------------------------- 153.6/994.0 kB 2.3 MB/s eta 0:00:01
     --------- ---------------------------- 256.0/994.0 kB 2.0 MB/s eta 0:00:01
     ---------- --------------------------- 276.5/994.0 kB 1.9 MB/s eta 0:00:01
     ---------------- --------------------- 430.1/994.0 kB 1.9 MB/s eta 0:00:01
     ----------------- -------------------- 450.6/994.0 kB 1.9 MB/s eta 0:00:01
     ----------------- -------------------- 460.8/994.0 kB 1.5 MB/s eta 0:00:01
     ----------------- -------------------- 460.8/994.0 kB 1.5 MB/s eta 0:00:01
     -------------------------- ----------- 696.3/994.0 kB 1.7 MB/s eta 0:00:01
     ----------------------------- -------- 778.2/994.0 kB 1.7 MB/s eta 0:00:01
     ---------------------------------- --- 890.9/994.0 kB 1.7 MB/s eta 0:00:01
     ------------------------------------ - 952

In [13]:
#MAX MIN COMPOSITION

def max_min_composition(R1, R2):
    result = np.zeros((len(R1), len(R2[0])))
    for i in range(len(R1)):
        for j in range(len(R2[0])):
            max_min = 0
            for k in range(len(R1[0])):
                max_min = max(min(R1[i][k], R2[k][j]), max_min)
            result[i][j] = max_min
    
    result = np.clip(result, 0, 1)
    return result


R1 = np.array([[0.3, 0.4, 0.7], [0.3, 0.5, 0], [0.4, 0.4, 1], [0.4, 0.5, 0.1]])
R2 = np.array([[0.3, 0.3, 0], [0.3, 0.5, 0.1], [0.4, 0.4, 0], [0.4, 0.5, 0.6]])
result = max_min_composition(R1, R2)
print("Max-Min Composition Result:")
print(result)

Max-Min Composition Result:
[[0.4 0.4 0.1]
 [0.3 0.5 0.1]
 [0.4 0.4 0.1]
 [0.3 0.5 0.1]]


In [2]:
import numpy as np
import skfuzzy as fuzz

def max_min_composition(R1, R2):
    result = np.zeros((len(R1), len(R2[0])))
    for i in range(len(R1)):
        for j in range(len(R2[0])):
            max_min = 0
            for k in range(len(R1[0])):
                max_min = max(min(R1[i][k], R2[k][j]), max_min)
            result[i][j] = max_min
    result = np.clip(result, 0, 1)
    return result

def take_input():
    while True:
        try:
            A = {k: float(input(f"Enter value for A[{k}]: ")) for k in ['a', 'b', 'c', 'd']}
            B = {k: float(input(f"Enter value for B[{k}]: ")) for k in ['a', 'b', 'c', 'd']}
            if all(0 <= val <= 1 for val in A.values()) and all(0 <= val <= 1 for val in B.values()):
                return A, B
            else:
                print("Values should be between 0 and 1. Please try again.")
        except ValueError:
            print("Invalid input. Please enter a number between 0 and 1.")

def main():
    A, B = take_input()

    option = int(input("""
    Select an option:
    1) Union
    2) Intersection
    3) Complement
    4) Difference
    5) Cartesian Product
    6) Max-Min Composition
    Enter your choice (1-6): """))

    Y = {}
    
    if option == 1:
        for A_key, B_key in zip(A, B):
            Y[A_key] = max(A[A_key], B[B_key])
        print('Fuzzy Set Union is:', Y)

    elif option == 2:
        for A_key, B_key in zip(A, B):
            Y[A_key] = min(A[A_key], B[B_key])
        print('Fuzzy Set Intersection is:', Y)

    elif option == 3:
        for A_key in A:
            Y[A_key] = 1 - A[A_key]
        print('Fuzzy Set Complement is:', Y)

    elif option == 4:
        for A_key, B_key in zip(A, B):
            Y[A_key] = max(A[A_key], 1 - B[B_key])
        print('Fuzzy Set Difference is:', Y)

    elif option == 5:
        cartesian_product = fuzz.cartprod(np.array(list(A.values())), np.array(list(B.values())))
        print("Cartesian product:", cartesian_product)

    elif option == 6:
        R1 = np.array([list(A.values())])
        R2 = np.array([list(B.values())])
        result = max_min_composition(R1, R2.T)
        print("Max-Min Composition Result:")
        print(result)

    else:
        print("Invalid option selected.")

if __name__ == "__main__":
    main()


Enter value for A[a]: 0.3
Enter value for A[b]: 0.4
Enter value for A[c]: 0.6
Enter value for A[d]: 0.5
Enter value for B[a]: 0.8
Enter value for B[b]: 0.1
Enter value for B[c]: 0.9
Enter value for B[d]: 0.3

    Select an option:
    1) Union
    2) Intersection
    3) Complement
    4) Difference
    5) Cartesian Product
    6) Max-Min Composition
    Enter your choice (1-6): 4
Fuzzy Set Difference is: {'a': 0.3, 'b': 0.9, 'c': 0.6, 'd': 0.7}
